M48
; DRILL file KiCad 10.0.6 date 2026-09-11T01:47:44
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-11T01:47:44+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X25.25Y-189.0
X27.0Y-22.5
X130.5Y-190.0
X133.25Y-22.5
M30
